# Generated by Django 5.2.3 on 2025-06-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollzone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='candidate_photos/'),
        ),
    ]
