# Generated by Django 5.2.3 on 2025-06-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollzone', '0002_candidate_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='photo',
        ),
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_profiles/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
