# Generated by Django 5.2.3 on 2025-06-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollzone', '0003_remove_candidate_photo_candidate_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='role',
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_photos/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
